---
- name: Include epel role
  ansible.builtin.include_role:
    name: buluma.epel

- name: Redhat | Rpm --import
  ansible.builtin.rpm_key:
    key: "{{ item.key }}"
    fingerprint: "{{ item.fingerprint }}"
    state: "{{ item.state }}"
  loop: "{{ _rpm_key }}"
  register: result
  until: result is succeeded

- name: Redhat | Yum-config-manager --add-repo
  ansible.builtin.yum_repository:
    file: "{{ item.file }}"
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    enabled: "{{ item.enabled }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    state: "{{ item.state }}"
  loop: "{{ _yum_repository }}"

- name: Redhat | Yum install teams
  ansible.builtin.yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ _yum }}"
  register: result
  until: result is succeeded
